# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-19 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0283_auto_20220609_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiarysite',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
