# Generated by Django 5.2.6 on 2025-10-01 03:23

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0303_alter_sectionquestion_parent_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='help_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='helppage',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='masterlistquestion',
            name='help_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterlistquestion',
            name='help_text_assessor',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
