# Generated by Django 5.2.10 on 2026-04-09 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0304_alter_globalsettings_help_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_questions', to='disturbance.proposaltypesection'),
        ),
    ]
