# Generated by Django 5.2.10 on 2026-04-09 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0305_alter_sectionquestion_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_sections', to='disturbance.masterlistquestion'),
        ),
        migrations.AlterField(
            model_name='spatialqueryquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='disturbance.masterlistquestion'),
        ),
    ]
