# Generated by Django 5.2.10 on 2026-04-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0306_alter_sectionquestion_question_and_spatialqueryquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaltypesection',
            name='add_to_search_select',
            field=models.BooleanField(default=False),
        ),
    ]
