# Generated by Django 5.2.10 on 2026-05-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0307_proposaltypesection_add_to_search_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaltype',
            name='add_to_proposal_type_section_list',
            field=models.BooleanField(default=False),
        ),
    ]
